// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Price       int32       `json:"price"`
	SellerEmail string      `json:"seller_email"`
}

type ListingView struct {
	ListingID string `json:"listing_id"`
	Views     int32  `json:"views"`
}

type Message struct {
	ID            string           `json:"id"`
	NegotiationID string           `json:"negotiation_id"`
	SenderEmail   string           `json:"sender_email"`
	SenderName    string           `json:"sender_name"`
	MessageText   string           `json:"message_text"`
	TimeSent      pgtype.Timestamp `json:"time_sent"`
	Status        pgtype.Text      `json:"status"`
}

type Negotiation struct {
	ID         string      `json:"id"`
	ListingID  string      `json:"listing_id"`
	BuyerEmail string      `json:"buyer_email"`
	Bid        pgtype.Int4 `json:"bid"`
	Ask        pgtype.Int4 `json:"ask"`
}
