// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	DeleteListing(ctx context.Context, listingID string) (Listing, error)
	ListingByID(ctx context.Context, listingID string) ([]Listing, error)
	ListingsByLikeName(ctx context.Context, listingName string) ([]Listing, error)
	ListingsBySellerEmail(ctx context.Context, sellerEmail string) ([]Listing, error)
	RecordListing(ctx context.Context, arg RecordListingParams) (Listing, error)
}

var _ Querier = (*Queries)(nil)
