// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	DeleteListing(ctx context.Context, listingID string) (Listing, error)
	ListingByID(ctx context.Context, listingID string) (ListingWithImageUrl, error)
	ListingViewsByID(ctx context.Context, listingID string) (int32, error)
	ListingsByLikeName(ctx context.Context, listingName string) ([]ListingWithImageUrl, error)
	ListingsBySellerEmail(ctx context.Context, sellerEmail string) ([]ListingWithImageUrl, error)
	ListingsByViews(ctx context.Context, arg ListingsByViewsParams) ([]ListingWithImageUrl, error)
	MessagesByNegotiationID(ctx context.Context, negotiationID string) ([]Message, error)
	NegotiationByListingIDAndBuyerEmail(ctx context.Context, arg NegotiationByListingIDAndBuyerEmailParams) (Negotiation, error)
	NegotiationsByEmail(ctx context.Context, email string) ([]NegotiationsByEmailRow, error)
	RecordListing(ctx context.Context, arg RecordListingParams) (Listing, error)
	RecordListingImages(ctx context.Context, arg RecordListingImagesParams) ([]ListingImage, error)
	RecordMessage(ctx context.Context, arg RecordMessageParams) (Message, error)
	RecordNegotiation(ctx context.Context, arg RecordNegotiationParams) (Negotiation, error)
	UpsertListingViews(ctx context.Context, listingID string) (ListingView, error)
}

var _ Querier = (*Queries)(nil)
